export const TABLE_ITEMS_MOCK = [
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
    {
      name: 'Amomé',
      age: 12,
      hobby: 'Play guitar',
      gender: 'male',
      phone: '394857362820',
      country: 'Brazil',
    },
  ];
